### ISSUE TITLE
额

### ISSUE THREAD

**Issue by Lunacia7** [WKJay/supermarket#1]
不会SQLSERVER,数据库连接一直失败..............

**Comment by Lunacia7** [comment]
能不能详细一点呢

**Comment by Lunacia7** [comment]
![default](https://s2.ax1x.com/2019/01/11/FXKvan.png)

**Comment by Lunacia7** [comment]
数据库已经连接上了,数据表结构只能逆推了......

**Comment by WKJay** [comment]
已经上传数据库文件，这是之前的一个备份数据库文件，不能保证他的准确性，但具有一定的参考价值
